openapi: 3.0.0
info:
  title: Sleep Efficiency API
  description:
    This API provides Real-time analysis of your sleep. Raw data provided by 2 Kaggle datasets (links provided in github README).
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8080/sleep-api
paths:
  /latest/{user_id}:
    parameters:
    - name: user_id
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Returns the user's latest sleep data recorded.
      operationId: controller.get_latest
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Latest'
                  
  /efficiency/{user_id}:
    parameters:
    - name: user_id
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Returns predicted sleep efficiency of the specified user.
      operationId: controller.get_user_efficiency
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Efficiency'
         
  /log/{user_id}:
    parameters:
    - name: user_id
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Returns a list of user's sleep logs in the database.
      operationId: controller.get_user_log
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LogItem'
                  
  /user/register:
    post:
      summary: Register a new user
      operationId: controller.user_register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
                - age
                - gender
                - smoke
                - exercise
              properties:
                username:
                  type: string
                password:
                  type: string
                age:
                  type: integer
                gender:
                  type: string
                  example: "`male` or `female` only"
                smoke:
                  type: boolean
                  example: "false"
                exercise:
                  type: integer
      responses:
        200:
          description: User registered successfully
        400:
          description: Bad request
            
  /user/edit:
      post:
        summary: Edit an existing user
        operationId: controller.user_edit
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - user_id
                  - username
                  - password
                  - age
                  - gender
                  - smoke
                  - exercise
                properties:
                  user_id:
                    type: integer
                  username:
                    type: string
                  password:
                    type: string
                  age:
                    type: integer
                  gender:
                    type: string
                    example: "`male` or `female` only"
                  smoke:
                    type: boolean
                    example: "false"
                  exercise:
                    type: integer
        responses:
          200:
            description: User edited successfully
          400:
            description: Bad request
          
  /user/login:
    post:
      summary: Login a user
      operationId: controller.user_login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: User logged in successfully
        400:
          description: Bad request
  
  

components:
  schemas:
    Latest:
      type: object
      properties:
        user_id:
          type: integer
        sleep_id:
          type: integer
        ts:
          type: string
        temperature:
          type: number
        humidity:
          type: number
        heartrate:
          type: integer
    Efficiency:
      type: object
      properties:
        light:
          type: number
          description: Percentage of time in Light sleep
        rem:
          type: number
          description: Percentage of time in REM sleep
        deep:
          type: number
          description: Percentage of time in Deep sleep
        smoke:
          type: boolean
          description: User's smoking status
        exercise:
          type: integer
          description: Number of user's exercises per week
        efficiency:
          type: number
          description: Predicted sleep efficiency
    LogItem:
      type: object
      properties:
        user_id:
          type: integer
        sleep_id:
          type: integer
        ts:
          type: string
        temperature:
          type: number
        humidity:
          type: number
        heartrate:
          type: integer
 
