openapi: 3.0.0
info:
  title: Sleep Efficiency API
  description:
    This API provides Real-time analysis of your sleep. Raw data provided by 2 Kaggle datasets (links provided in github README).
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8080/sleep-api
paths:
  /latest/{username}:
    parameters:
    - name: username
      in: path
      required: true
      schema:
        type : string
    get:
      summary: Returns the user's latest sleep data recorded.
      operationId: controller.get_latest
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Latest'
  /efficiency/{username}:
    parameters:
    - name: username
      in: path
      required: true
      schema:
        type : string
    get:
      summary: Returns predicted sleep efficiency of the specified user.
      operationId: controller.get_user_efficiency
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Efficiency'
          links:
            stations:
              operationId: controller.get_stations_in_basin
              parameters:
                basinId: $response.body#/basinId
            annualRainfall:
              operationId: controller.get_basin_annual_rainfall
              parameters:
                basinId: $response.body#/basinId
            avgMonthlyRainfalls:
              operationId: controller.get_basin_monthly_average
              parameters:
                basinId: $response.body#/basinId
  /log/{username}:
    parameters:
    - name: username
      in: path
      required: true
      schema:
        type : string
    get:
      summary: Returns a list of user's sleep logs in the database.
      operationId: controller.get_user_log
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LogItem'
  

components:
  schemas:
    Latest:
      type: object
      properties:
        ts:
          type: string
        temperature:
          type: number
        humidity:
          type: number
        heartrate:
          type: integer
    Efficiency:
      type: object
      properties:
        light:
          type: number
          description: Percentage of time in Light sleep
        rem:
          type: number
          description: Percentage of time in REM sleep
        deep:
          type: number
          description: Percentage of time in Deep sleep
        smoke:
          type: boolean
          description: User's smoking status
        exercise:
          type: integer
          description: Number of user's exercises per week
        efficiency:
          type: number
          description: Predicted sleep efficiency
    LogItem:
      type: object
      properties:
        userId:
          type: integer
        ts:
          type: string
        temp:
          type: number
        humidity:
          type: number
        heartrate:
          type: integer
 
