# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Latest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ts: str=None, temperature: float=None, humidity: float=None, heartrate: int=None):  # noqa: E501
        """Latest - a model defined in Swagger

        :param ts: The ts of this Latest.  # noqa: E501
        :type ts: str
        :param temperature: The temperature of this Latest.  # noqa: E501
        :type temperature: float
        :param humidity: The humidity of this Latest.  # noqa: E501
        :type humidity: float
        :param heartrate: The heartrate of this Latest.  # noqa: E501
        :type heartrate: int
        """
        self.swagger_types = {
            'ts': str,
            'temperature': float,
            'humidity': float,
            'heartrate': int
        }

        self.attribute_map = {
            'ts': 'ts',
            'temperature': 'temperature',
            'humidity': 'humidity',
            'heartrate': 'heartrate'
        }
        self._ts = ts
        self._temperature = temperature
        self._humidity = humidity
        self._heartrate = heartrate

    @classmethod
    def from_dict(cls, dikt) -> 'Latest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Latest of this Latest.  # noqa: E501
        :rtype: Latest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ts(self) -> str:
        """Gets the ts of this Latest.


        :return: The ts of this Latest.
        :rtype: str
        """
        return self._ts

    @ts.setter
    def ts(self, ts: str):
        """Sets the ts of this Latest.


        :param ts: The ts of this Latest.
        :type ts: str
        """

        self._ts = ts

    @property
    def temperature(self) -> float:
        """Gets the temperature of this Latest.


        :return: The temperature of this Latest.
        :rtype: float
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature: float):
        """Sets the temperature of this Latest.


        :param temperature: The temperature of this Latest.
        :type temperature: float
        """

        self._temperature = temperature

    @property
    def humidity(self) -> float:
        """Gets the humidity of this Latest.


        :return: The humidity of this Latest.
        :rtype: float
        """
        return self._humidity

    @humidity.setter
    def humidity(self, humidity: float):
        """Sets the humidity of this Latest.


        :param humidity: The humidity of this Latest.
        :type humidity: float
        """

        self._humidity = humidity

    @property
    def heartrate(self) -> int:
        """Gets the heartrate of this Latest.


        :return: The heartrate of this Latest.
        :rtype: int
        """
        return self._heartrate

    @heartrate.setter
    def heartrate(self, heartrate: int):
        """Sets the heartrate of this Latest.


        :param heartrate: The heartrate of this Latest.
        :type heartrate: int
        """

        self._heartrate = heartrate
