# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LogItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_id: int=None, ts: str=None, temp: float=None, humidity: float=None, heartrate: int=None):  # noqa: E501
        """LogItem - a model defined in Swagger

        :param user_id: The user_id of this LogItem.  # noqa: E501
        :type user_id: int
        :param ts: The ts of this LogItem.  # noqa: E501
        :type ts: str
        :param temp: The temp of this LogItem.  # noqa: E501
        :type temp: float
        :param humidity: The humidity of this LogItem.  # noqa: E501
        :type humidity: float
        :param heartrate: The heartrate of this LogItem.  # noqa: E501
        :type heartrate: int
        """
        self.swagger_types = {
            'user_id': int,
            'ts': str,
            'temp': float,
            'humidity': float,
            'heartrate': int
        }

        self.attribute_map = {
            'user_id': 'userId',
            'ts': 'ts',
            'temp': 'temp',
            'humidity': 'humidity',
            'heartrate': 'heartrate'
        }
        self._user_id = user_id
        self._ts = ts
        self._temp = temp
        self._humidity = humidity
        self._heartrate = heartrate

    @classmethod
    def from_dict(cls, dikt) -> 'LogItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LogItem of this LogItem.  # noqa: E501
        :rtype: LogItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> int:
        """Gets the user_id of this LogItem.


        :return: The user_id of this LogItem.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this LogItem.


        :param user_id: The user_id of this LogItem.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def ts(self) -> str:
        """Gets the ts of this LogItem.


        :return: The ts of this LogItem.
        :rtype: str
        """
        return self._ts

    @ts.setter
    def ts(self, ts: str):
        """Sets the ts of this LogItem.


        :param ts: The ts of this LogItem.
        :type ts: str
        """

        self._ts = ts

    @property
    def temp(self) -> float:
        """Gets the temp of this LogItem.


        :return: The temp of this LogItem.
        :rtype: float
        """
        return self._temp

    @temp.setter
    def temp(self, temp: float):
        """Sets the temp of this LogItem.


        :param temp: The temp of this LogItem.
        :type temp: float
        """

        self._temp = temp

    @property
    def humidity(self) -> float:
        """Gets the humidity of this LogItem.


        :return: The humidity of this LogItem.
        :rtype: float
        """
        return self._humidity

    @humidity.setter
    def humidity(self, humidity: float):
        """Sets the humidity of this LogItem.


        :param humidity: The humidity of this LogItem.
        :type humidity: float
        """

        self._humidity = humidity

    @property
    def heartrate(self) -> int:
        """Gets the heartrate of this LogItem.


        :return: The heartrate of this LogItem.
        :rtype: int
        """
        return self._heartrate

    @heartrate.setter
    def heartrate(self, heartrate: int):
        """Sets the heartrate of this LogItem.


        :param heartrate: The heartrate of this LogItem.
        :type heartrate: int
        """

        self._heartrate = heartrate
